### ISSUE TITLE
E117: Unknown function: minimap#init

### ISSUE THREAD

**Issue by AlexBurdu** [koron/minimap-vim#24] opened 2016-02-19 19:51 UTC
I can't start it at all. Installed using Vundle by adding to my .vimrc
`Plugin 'koron/minimap-vim'` 

On starting gvim I get 

`Error detected while processing VimEnter Auto commands for "*":
E117: Unknown function: minimap#init`

Obviously if I run `:MinimapSync` I get `E492: Not an editor command: MinimapSync`

**Comment by koron** [comment] 2016-02-20 01:24
Please try [Regular Installation](https://github.com/koron/minimap-vim#regular-installation)

**Comment by AlexBurdu** [comment] 2016-02-20 12:28
works with regular installation

**Comment by koron** [comment] 2016-02-20 13:37
It seems caused by vundle specific.
I won't investigate it.  So I close this anyway.

If you find the fix, please make a PR.

**Closed as completed by koron** 2016-02-20 13:37 UTC
Labels: wontfix
